[project]
name = "zic"
version = "0.1.0"
keywords = ["release-date:2026-09-20"]
description = "A local music player desktop app"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "appdirs>=1.4.4",
    "pyside6>=6.11.2",
    "toml>=0.10.2",
    "mutagen>=1.48.1",
    "numpy>=2.5.2",
    "pillow>=12.3.0",
    "click>=8.5.0",
    "requests>=2.34.2",
    "secret-type>=0.3.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
zic = "zic.main:main"

[tool.setuptools.package-data]
zic = [
    "resources/**/*",
    "schema.sql"
]

[tool.setuptools.exclude-package-data]
"*" = [
    "*.pyc",
]
